### PR TITLE
update amp-ad config

### PR DESCRIPTION
**Pull request by avanlinden**
Changes for the amp-ad configuration setting for the AWS deployment of dccvalidator. 

- remove url 
- hide study documentation tab
- change RNAseq assay template from json schema to synID of template file
- update required columns in individual and biospecimen metadata files

### CODE REVIEW

**Comment by avanlinden** [comment]
@danlu1 It looks like the R-CMD-check workflows are failing because of some missing dependencies (devtools, sometimes optpartse, sometimes httr). Is that something that needs to be fixed, or could we merge the changes to the amp-ad config without worrying about the failing checks?

**Comment by danlu1** [comment]
@avanlinden it should be due to some GH actions having been deprecated. I believe we can bypass this check since we didn't make any fundamental changes to the app.

**Comment by avanlinden** [comment]
Ok great! I don't have write access to the repo, can you either give me write access or merge the PR? Thanks!

**Comment by danlu1** [comment]
@avanlinden just granted you admin permission to the repo.

**Comment by avanlinden** [comment]
thank you!

**Pull request merged**
